sinsquare: waves.h waves_gen.c main_waves.c
	clang -Wall -lm -o sinsquare waves_gen.c main_waves.c
evidence: waves.h waves_gen.c evidence_waves_gen.c
	clang -Wall -lm -o ev waves_gen.c evidence_waves_gen.c 

